### ISSUE TITLE
Allow use of eventmachine greater than 1.0.7

### ISSUE THREAD

**Issue by sax** [nats-io/ruby-nats#103]
We have used `git bisect` to determine that [this commit](https://gist.github.com/libc/bced7e3402d8aa482681) in eventmachine is what leads to test failures on OS X.

We currently have conflicting dependencies on eventmachine, and would like to update to a newer version, but are stuck because of nats' hard dependency of `= 1.0.7`.

**Comment by wallyqs** [comment]
Thanks for sharing, will take a look.  This commit right? => https://github.com/eventmachine/eventmachine/commit/cac55972ab1b1b10ef57ef34fd3565ea50c812c8

**Comment by sax** [comment]
That's it.

**Comment by sax** [comment]
Sorry, I thought that was the commit link I was pasting!

**Comment by sax** [comment]
Thank you!

I was curious if there was a (rough) plan on releasing a new version of the gem. If a new version was not going to be officially released in the near term, would it be possible to have this pre-released to rubygems?

My main point in asking is that we've seen segfaults in the current version of eventmachine, and were hoping to update that as soon as possible.

Thanks!

**Comment by wallyqs** [comment]
Currently aiming to make a (pre?)-release of the gem probably next week after doing a couple of TLS related pending updates.  Segfaults you mention are with 1.0.7? Next release would be allowing use of 1.2.0.1 (currently latest).

**Comment by sax** [comment]
segfaults are on 1.0.9.1, which someone did some voodoo to force through our Gemfile. It looks like a double free on releasing the event machine.

It might be a fault of our code, but we were hoping to rule out the old version of EM.

**Comment by wallyqs** [comment]
OK, thanks for the info

**Comment by wallyqs** [comment]
@sax ruby-nats client [0.7.0](https://github.com/nats-io/ruby-nats/releases/tag/v0.7.0) is now on [rubygems](https://rubygems.org/gems/nats/versions/0.7.0), let me know if it works for you
