### ISSUE TITLE
SRV record support

### ISSUE THREAD

**Issue by ripienaar** [nats-io/ruby-nats#107]
hello,

I am considering adding SRV record support for finding the nats servers.

I'm thinking someting like `NATS.start(:srv_domain => "example.net")` would then lookup `_nats-server._tcp.example.net` and connect to whatever it finds there.  In the order sorted by priority.

If given along with `:servers` it will try SRV first and then fall back to the hardcoded list.

Would you accept such a patch if I wrote it - don't want to spend a bunch of time and then discover you won't want it.

**Comment by wallyqs** [comment]
Thought about this one, and think that for now we should leave the responsibility of feeding the initial list of servers to the caller.  We could always make a query for SRV records before trying to establish the connection for example in any case:

```ruby
  def connect!
    # Do SRV records lookup...
    nats_servers = lookup_nats_service
    if nats_servers.empty?
      $stderr.puts "No available servers!"
      exit 1
    end

    puts "Available servers: #{nats_servers}"
    @nats = NATS.connect(:servers => nats_servers) do 
      puts "Connected to #{@nats.connected_server}"
    end
    @nats.subscribe("help") do |msg|
      puts "Got: #{msg}"
    end
    @nats.on_reconnect do
      puts "Reconnected to #{@nats.connected_server}"
    end
    @nats.on_error do |e|
      next unless e.kind_of? NATS::ConnectError
      $stderr.puts "ERROR: #{e}"
      # e.g. could discover new set of  servers and try to establish connection again.
      EM.add_timer(2) { connect! }
    end
  end
```

Although harmless think we should leave this servers discovery part out from the client for now, and instead follow the server discovery semantics which could be happening soon in other clients too: https://github.com/nats-io/gnatsd/issues/126

**Comment by ripienaar** [comment]
Ah, I was not aware of the issue over at the gnatsd project, ok.

Yeah I have SRV code already close to above so figured it would be a good general addition since that's a common pattern.

And thanks for the example above `EM.add_timer(2) { connect! }` is handy, I was wondering why my reconnects werent working with the examples in the docs here

We can close this issue then I guess
