### ISSUE TITLE
correctly handling retries

### ISSUE THREAD

**Issue by ripienaar** [nats-io/ruby-nats#108]
hello,

My use care requires the client to just infinitely reconnect as long as it can, ideally I want to also show useful logs on failure, retry and reconnection.

Your README shows:

```
NATS.start(:servers => ['nats://127.0.0.1:4222', 'nats://127.0.0.1:4223']) do |c|
  puts "NATS is connected to #{c.connected_server}"
  c.on_reconnect do
    puts "Reconnected to server at #{c.connected_server}"
  end
end

opts = {
  :dont_randomize_servers => true,
  :reconnect_time_wait => 0.5,
  :max_reconnect_attempts = 10,
  :servers => ['nats://127.0.0.1:4222', 'nats://127.0.0.1:4223', 'nats://127.0.0.1:4224']
}

NATS.connect(opts) do |c|
  puts "NATS is connected!"
end
```

This cannot possibly be right.  When `on_reconnect` is called `connected?` is false and `connected_server` will return nil.

So I've been fruitlessly trying to write something that will:

   * Attempt to connect
   * Attempt to reconnect for ever
   * Log every time when its failed - indicating what server failed
   * Log every time when its retrying - what server its trying
   * Log every time when its connected - what server it connected to

These logs are essential for someone trying to debug whats failed and whats working.

Appears to me this should be enough (except maybe logging which server failed):

```
options = {
  :max_reconnect_attempts => -1,
  :reconnect_time_wait => 1,
  :dont_randomize_servers => true,
  :servers => server_list
}

NATS.on_error do |e|
   Log.error("Error in NATS connection: %s: %s" % [e.class, e.to_s])
   next unless e.is_a?(NATS::ConnectError)
   raise(e)
end

 NATS.start(options) do |c|
   Log.info("NATS is connected to %s" % c.connected_server)

   c.on_reconnect do
      Log.info("Reconnecting after connection failure '%s'" % c.connected_server)
   end
end
```

As above in the `on_reconnect` block `c.connected_server` is nil, and `NATS.start` sets the block to be the `on_connect` block.  This block does not get called once successfully reconnected because you track this via `@conn_cb_called` and only call it once.

So what's the right way to achieve the logging I desire? This is no doubt easy for someone who knows EM but it's a bit of a spaghetti monster if you don't :)

**Comment by wallyqs** [comment]
Hi, it is be possible right now to log when it connected/reconnected and to which server as well as reconnecting forever via `:max_reconnect_attempts => -1`, for example with something like:

```ruby
require 'nats/client'
$stdout.sync = true

class Service

  def initialize(opts={})
    @nats = nil
    @servers = opts[:servers] || ["nats://127.0.0.1:4222"]
  end

  def start!
    puts "Available servers: #{@servers}"
    @nats = NATS.connect(:servers => @servers, :max_reconnect_attempts => -1, :reconnect_time_wait => 1) do
      puts "Connected to #{@nats.connected_server}"
    end
    @nats.subscribe("help") do |msg|
      puts "Got: #{msg}"
    end
    @nats.on_reconnect do
      puts "Reconnected to #{@nats.connected_server}"
    end
    @nats.on_error do |e|
      puts "Nats Error: #{e}"
    end
    EM.error_handler do |e|
      puts "EventMachine error: #{e}"
    end
  end
end

EM.run do
  service = Service.new(:servers => ["nats://127.0.0.1:4223", "nats://127.0.0.1:4224", "nats://127.0.0.1:4225"])
  service.start!
end
```

You could get something like:

```
Available servers: ["nats://127.0.0.1:4223", "nats://127.0.0.1:4224", "nats://127.0.0.1:4225"]
Connected to nats://127.0.0.1:4224
Reconnected to nats://127.0.0.1:4225
Reconnected to nats://127.0.0.1:4224
...
```

For the other cases you mention, the client is currently missing the `disconnected_cb` and `closed_cb` which are now present in other clients and could be used to add logging for when disconnection failed and there is a pending reconnection attempt, I will look into adding those along with the TLS updates.

**Comment by ripienaar** [comment]
OK, I'll try this - from my tests `on_reconnect` does not have a valid `connected_server`, might be a SSL only bug.  Will try your code with and without SSL and see

thanks

**Comment by ripienaar** [comment]
Yeah, with TLS the reconnect logging doesn't have a valid server to log:

https://github.com/nats-io/ruby-nats/blob/master/lib/nats/client.rb#L601

That doesnt set `@connected=true` and then:

https://github.com/nats-io/ruby-nats/blob/master/lib/nats/client.rb#L760

Doesn't return the current server.

My code works when not in TLS, so that's what caused the confusion :) Definitely a TLS related bug

**Comment by ripienaar** [comment]
Pinging on this one too - last comment here demonstrates the bug in question

**Comment by wallyqs** [comment]
Fix for this in master now, example usage added here: https://github.com/nats-io/ruby-nats/blob/f702ee531f36d7f12cae7005814f232abcf4de09/examples/tls.rb
