### ISSUE TITLE
timing issue around @pending queue

### ISSUE THREAD

**Issue by ripienaar** [nats-io/ruby-nats#109]
I cannot show you code that reproduce this since simple code just works in most cases, seems to happen only on a very slow under spec VM I have when running a number of things on it...which suggests a timing issue. 

But the symptoms are:

  * published messages just vanish
  * published messages get stuck internally to the Nats::Client and only get sent at a later stage

The client is written around an array of pending messages and a flush that happens in `EM.next_tick`, this is problematic since it assumes the work in the method is done before `EM.next_tick` happens.

https://github.com/nats-io/ruby-nats/blob/d0556a0715c04eb395ade2cf0a9b7b806cd87ff3/lib/nats/client.rb#L737

In that code should adding the command to the array not complete by the time `next_tick` happens - which could really be any time - messages will be lost or delayed.

I added some debug puts messages and can definitely see the `next_tick` driven flush happen mid adding of the command to the pending list - and flush will nil the pending list so it looses messages.  

So depending on when exactly the `next_tick` fires it either nils the queue - so messages vanish, or it does nothing leaving the messages on the queue and no flush gets scheduled until for some other reason in the future a flush is called.

Changing the `send_command` method like this:

```
def send_command(command, priority = false) #:nodoc:
  needs_flush = connected? && @pending.nil?

  @pending ||= []
  @pending << command unless priority
  @pending.unshift(command) if priority
  @pending_size += command.bytesize

  EM.next_tick { flush_pending } if needs_flush

  flush_pending if (connected? && @pending_size > MAX_PENDING_SIZE)
  if (@options[:fast_producer_error] && pending_data_size > FAST_PRODUCER_THRESHOLD)
    err_cb.call(NATS::ClientError.new("Fast Producer: #{pending_data_size} bytes outstanding"))
  end
  true
end
```

which ensures the `next_tick` driven `flush_pending` doesnt happen mid creating of the data seems to resolve it reliably for me on my slow machine.

**Comment by ripienaar** [comment]
any update on this? pretty much a show stopper for me.

**Comment by wallyqs** [comment]
Hi, have the spec running now on latest EM and think we can adopt this change to potentially avoid the race you mention (getting green including the suggested behavior in PR).
Will update master today with the related changeset for this, thanks.

**Comment by wallyqs** [comment]
Pushed the suggested fix to master and build seems stable, let me know if it works out for you. Thanks.

**Comment by ripienaar** [comment]
sweet thanks
