### ISSUE TITLE
Differentiate between errors that close the connection & not

### ISSUE THREAD

**Issue by pmenglund** [nats-io/ruby-nats#32]
There is no difference between a NATS::ServerError that closes the connection (like AUTH_REQUIRED) and one that keeps the connection open - this makes it hard to deal with this on the client side.

It would be nice to have something like NATS::ServerError::Fatal that means the client has to retry the connection.

**Comment by mcqueary** [comment]
Closing due to age. If anyone thinks this is still an issue, please let us know.
