### ISSUE TITLE
cannot see published messages when useing Go NATS server

### ISSUE THREAD

**Issue by rtacconi** [nats-io/ruby-nats#81]
I am using gnats server 0.5.6, ruby-nats 0.5.0.beta.12 or 0.5.0.beta.16. When I use the Go pub and sub examples it works. If I use the examples provided here https://github.com/derekcollison/ruby-nats/blob/cluster/examples/auth_pub.rb and here https://github.com/derekcollison/ruby-nats/blob/cluster/examples/auth_sub.rb I can see that the message is published (by using the -d option in the nat server) but the subscriber does not print anything. I have a feeling the the ruby-nats gem is working with some old version of the gnatsd server but probably server 0.5.6 is not working.

**Comment by derekcollison** [comment]
This still an issue?

**Comment by rtacconi** [comment]
I just tried now, after months, yes still the same issue. This is completing blocking me. gnats server is 0.6.0. Ruby client is 0.5.0.

**Comment by derekcollison** [comment]
ok will take a look and see what is going on..

**Comment by derekcollison** [comment]
Are you running gnatsd with a username and password?

try ``gnatsd --user foo --pass bar``

Then try 

``ruby auth_sub.rb foo bar test &``
``ruby auth_pub.rb foo bar test hello``

**Comment by rtacconi** [comment]
I did it, what I saw was:
Published on [test] : 'hello'

I did not see received

**Comment by derekcollison** [comment]
ok I will take a look today..

**Comment by derekcollison** [comment]
ok the issue was that we did not put a closure on the publish and simply called stop, so the message actually never made it to the server. The pub.rb example did it right, so changed it to mimic that with the closure to Publish() calling Stop().

https://github.com/nats-io/ruby-nats/commit/e8e1500fc94511f197d1d58f739baac8ea71ce7b

**Comment by rtacconi** [comment]
Thank you!

**Comment by derekcollison** [comment]
No problem, thanks for reporting the issue..
