### ISSUE TITLE
NATS client forgets all servers and never reconnects

### ISSUE THREAD

**Issue by fraenkel** [nats-io/ruby-nats#87]
While this seems to be the expected behavior as coded, you questioned whether its correct.
https://github.com/nats-io/ruby-nats/blob/master/lib/nats/client.rb#L793

For us, this is the wrong behavior since
1. its expected. A rolling upgrade of gnatsd servers will cause a sequence of failed connects. The servers should not be removed.
2. the only way to detect this situation is to add my own err callback and look at the server_pool. However, it seems that process_disconnect may be called multiple times, but not in all cases which makes it very difficult to know when it's safe to rebuild a nats client. Although in our case I believe our only option is to restart our process since we cannot hand out a new NATS client.

I would like to either remove this behavior or at least add an option to never remove a server regardless of the situation and just cycle through them.

**Comment by fraenkel** [comment]
I also noticed that server[:was_connected] is only ever set to true but never set back to false if we are rotating to another server.

**Comment by derekcollison** [comment]
Thanks, will take a look.

**Comment by derekcollison** [comment]
Needed to lock EM to 1.0.7 to get tests passing, etc.. FYI
