### ISSUE TITLE
Do not throw a warning when epoll is not supported.

### ISSUE THREAD

**Issue by Gerg** [nats-io/ruby-nats#89]
Using the client on OSX results in the following warning: `nats-0.5.1/lib/nats/client.rb:154: warning: epoll is not supported on this platform`. It would be great to suppress this warning.

Here is a PR that does something similar: https://github.com/tweetstream/tweetstream/pull/182

**Comment by derekcollison** [comment]
Which version of EM are you running?

**Comment by Gerg** [comment]
1.0.8

**Comment by wallyqs** [comment]
Ok just made a PR to try to address this.  Found a similar issue in em-proxy (https://github.com/igrigorik/em-proxy/issues/48), this seems to be needed due to latest changes in EM 1.0.8.

**Comment by Gerg** [comment]
:+1:
