### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by wendorf** [nats-io/ruby-nats#93]
https://github.com/nats-io/ruby-nats/commit/d9fa4374e9547df30f595abff96d7f38575b07a2 looks delightful. Can we get a new version of the gem that includes it?

I'd love to see ".gem/ruby/2.2.4/gems/nats-0.5.1/lib/nats/client.rb:154: warning: epoll is not supported on this platform" show up less frequently in my logs.

Thanks!

**Comment by wallyqs** [comment]
Thanks, though have you tried with latest release of eventmachine instead?  The behavior change from eventmachine which was causing that has been reverted since: https://github.com/eventmachine/eventmachine/issues/638

**Comment by wendorf** [comment]
On your recommendation, I bumped to eventmachine 1.0.9.1 from 1.0.8, which successfully cleaned up the warnings.
